//! `sample_table` — `SELECT * FROM "<schema>"."<table>" LIMIT n` with the
//! caller's grant row cap.
//!
//! This is the first place we build SQL with an identifier from caller input.
//! Postgres bind parameters can't bind identifiers (only values), so we
//! validate-then-quote: each identifier must match
//! `^[A-Za-z_][A-Za-z0-9_]*$` before it lands inside `"..."`. Anything else is
//! rejected before SQL is built.

use std::time::Instant;

use serde::{Deserialize, Serialize};
use serde_json::Value;
use sqlx::PgPool;

use crate::auth::Identity;
use crate::authz::{self, Decision, PermissionsCache, cache::load_or_empty};
use crate::config::{Action, ConfigFile, Database, Grant, Server};
use crate::exec::{AdapterRegistry, ExecError, ExecQuery};
use crate::transport::jsonrpc::{ErrorObject, Response};

use super::audit_dispatch::{
    AuditHeader, Outcome, RequestContext, audit_dispatch, error_outcome, success_outcome,
};

const TOOL_NAME: &str = "sample_table";
const DEFAULT_SCHEMA: &str = "public";
/// Hard floor on rows sampled when no grant constraint and no caller limit
/// apply. `sample_table` exists for "peek at the shape of the data" — small
/// by default, never giant.
const DEFAULT_SAMPLE_LIMIT: u32 = 10;

#[derive(Debug, Deserialize)]
pub struct Arguments {
    pub server: String,
    pub database: String,
    pub table: String,
    #[serde(default)]
    pub schema: Option<String>,
    #[serde(default)]
    pub limit: Option<u32>,
}

#[derive(Debug, Serialize)]
struct SuccessPayload<'a> {
    columns: &'a [String],
    rows: &'a [Vec<Value>],
    truncated: bool,
    elapsed_ms: u64,
}

#[allow(clippy::too_many_arguments)]
pub async fn run(
    id: Value,
    identity: &Identity,
    config: &ConfigFile,
    registry: &AdapterRegistry,
    permissions_cache: Option<&PermissionsCache>,
    state_db: Option<&PgPool>,
    request_ctx: &RequestContext,
    arguments: Option<Value>,
) -> Response {
    let args: Arguments = match arguments.map(serde_json::from_value::<Arguments>) {
        Some(Ok(a)) => a,
        _ => {
            return Response::error(
                id,
                ErrorObject::invalid_params(
                    "sample_table requires `server`, `database`, `table` arguments",
                ),
            );
        }
    };

    let header = AuditHeader {
        tool: TOOL_NAME,
        server: Some(&args.server),
        database: Some(&args.database),
        // SQL generated by us; the audit row captures the gateway's intent
        // (tool + (schema, table) — sample_table doesn't take a `reason`).
        sql: None,
        reason: None,
    };
    let db_grants = match load_or_empty(permissions_cache, identity).await {
        Ok(g) => g,
        Err(err) => {
            tracing::error!(%err, "permissions cache load failed");
            let resp = error_outcome(id.clone(), "internal", "permissions_cache_load_failed");
            let work = async move { resp };
            return audit_dispatch(id, identity, state_db, request_ctx, header, work).await;
        }
    };
    let work = compute_outcome(id.clone(), identity, config, registry, &db_grants, &args);
    audit_dispatch(id, identity, state_db, request_ctx, header, work).await
}

async fn compute_outcome(
    id: Value,
    identity: &Identity,
    config: &ConfigFile,
    registry: &AdapterRegistry,
    db_grants: &[Grant],
    args: &Arguments,
) -> Outcome {
    let Some((server, database)) = find_server_db(config, &args.server, &args.database) else {
        return forbidden(id);
    };

    let decision = authz::evaluate_effective(
        identity,
        Action::SchemaRead,
        &server.name,
        &database.name,
        &config.permissions,
        db_grants,
    );
    let constraints = match decision {
        Decision::Allow { constraints } => constraints,
        Decision::Deny => return forbidden(id),
    };

    let schema = args.schema.as_deref().unwrap_or(DEFAULT_SCHEMA);
    if !is_safe_identifier(schema) {
        return invalid_identifier(id, "schema");
    }
    if !is_safe_identifier(&args.table) {
        return invalid_identifier(id, "table");
    }

    let row_limit = effective_row_limit(args.limit, constraints.row_limit);
    // Fetch one extra row so the gateway-side truncation flag can fire when
    // the table has more rows than the requested sample. LIMIT is a u32
    // produced by us — purely numeric, no injection risk. Identifier
    // interpolation is safe because both identifiers passed
    // `is_safe_identifier`.
    let sql_limit = row_limit.saturating_add(1);
    let sql = format!(
        "SELECT * FROM \"{schema}\".\"{table}\" LIMIT {sql_limit}",
        table = args.table,
    );
    let timeout_ms = constraints.statement_timeout_ms;

    // Wall clock starts before pool open so error paths still carry
    // `duration_ms` into the audit row — spec 07 requires it on every call.
    let started = Instant::now();
    let adapter = match registry.get_or_open(server, database).await {
        Ok(a) => a,
        Err(err) => return outcome_from_exec_error(id, err, started),
    };

    let query = ExecQuery {
        sql: &sql,
        binds: &[],
        statement_timeout_ms: timeout_ms,
        row_limit,
    };
    match adapter.execute(query).await {
        Ok(result) => {
            let elapsed = i64::try_from(result.elapsed_ms).unwrap_or(i64::MAX);
            let row_count = i64::try_from(result.rows.len()).unwrap_or(i64::MAX);
            let truncated = result.truncated;
            let payload = SuccessPayload {
                columns: &result.columns,
                rows: &result.rows,
                truncated,
                elapsed_ms: result.elapsed_ms,
            };
            let text = match serde_json::to_string(&payload) {
                Ok(t) => t,
                Err(_) => return error_outcome(id, "internal", "failed to serialize result"),
            };
            success_outcome(id, text, Some(elapsed), Some(row_count), Some(truncated))
        }
        Err(err) => outcome_from_exec_error(id, err, started),
    }
}

/// Per spec 08 + the `validate_role` precedent: identifiers are exactly
/// `^[A-Za-z_][A-Za-z0-9_]*$`. Anything else (spaces, quotes, semicolons,
/// dashes, even valid-but-quoted-in-Postgres names like `My Table`) is
/// rejected. Conservative — safer than trying to escape arbitrary input.
fn is_safe_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn invalid_identifier(id: Value, field: &'static str) -> Outcome {
    error_outcome(
        id,
        "invalid_argument",
        &format!("`{field}` must match ^[A-Za-z_][A-Za-z0-9_]*$"),
    )
}

fn forbidden(id: Value) -> Outcome {
    error_outcome(id, "forbidden", "no grants for this server/database")
}

fn find_server_db<'a>(
    config: &'a ConfigFile,
    server_name: &str,
    database_name: &str,
) -> Option<(&'a Server, &'a Database)> {
    let server = config.servers.iter().find(|s| s.name == server_name)?;
    let database = server.databases.iter().find(|d| d.name == database_name)?;
    Some((server, database))
}

fn effective_row_limit(caller: Option<u32>, grant: Option<u32>) -> u32 {
    let caller = caller.unwrap_or(DEFAULT_SAMPLE_LIMIT);
    match grant {
        Some(grant_cap) => caller.min(grant_cap),
        None => caller,
    }
}

fn outcome_from_exec_error(id: Value, err: ExecError, started: Instant) -> Outcome {
    let owned;
    let (code, message): (&str, &str) = match err {
        ExecError::Timeout => ("timeout", "query exceeded the configured statement_timeout"),
        ExecError::Connection | ExecError::Unavailable => {
            ("unavailable", "target database is unreachable")
        }
        ExecError::Sql => ("syntax_error", "the target DB rejected the SQL"),
        ExecError::Forbidden(reason) => {
            owned = format!("sample rejected by gateway: {reason}");
            ("forbidden_sql", owned.as_str())
        }
        ExecError::PasswordUnresolved { .. }
        | ExecError::UnsupportedAdapter(_)
        | ExecError::NotImplemented { .. } => ("internal", "server-side configuration error"),
    };
    let mut outcome = error_outcome(id, code, message);
    outcome.elapsed_ms = Some(i64::try_from(started.elapsed().as_millis()).unwrap_or(i64::MAX));
    outcome
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_safe_identifier_accepts_valid_names() {
        for ok in [
            "users",
            "_private",
            "public",
            "USERS",
            "user_accounts",
            "t1",
            "_t_2",
            "X",
        ] {
            assert!(is_safe_identifier(ok), "should accept `{ok}`");
        }
    }

    #[test]
    fn is_safe_identifier_rejects_anything_else() {
        for bad in [
            "",                        // empty
            "1users",                  // starts with digit
            "user accounts",           // space
            "users; DROP TABLE x; --", // injection attempt
            "\"users\"",               // pre-quoted
            "user-accounts",           // hyphen
            "users.private",           // dot
            "用户",                    // non-ASCII
            "users\nDROP",             // newline
            "users'",                  // quote
        ] {
            assert!(!is_safe_identifier(bad), "should reject `{bad}`");
        }
    }

    #[test]
    fn effective_row_limit_takes_smaller() {
        assert_eq!(effective_row_limit(Some(20), Some(5)), 5);
        assert_eq!(effective_row_limit(Some(5), Some(20)), 5);
        assert_eq!(effective_row_limit(Some(50), None), 50);
        assert_eq!(effective_row_limit(None, Some(3)), 3);
        assert_eq!(effective_row_limit(None, None), DEFAULT_SAMPLE_LIMIT);
    }
}
